/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bmw.gltf
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/bmw-m6-gt3-shiny-evil-27956e4ebaaa468980bc48e50106d5c6
Title: BMW M6 GT3 Shiny & Evil
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bmw.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.8}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.BADGES} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.BLACKCHROME} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.BLACKPLASTIC} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.BLUERED} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.BMW_M6_GT3_by_Alex_Ka} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.BOTTOM} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.BRAKEDISC} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.BRAKELIGHT} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.DETAILS} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.EMBLEM} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.FOFLIGHT} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.FUELcap} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.GRILL} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.HEADLIGHT} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.INTERIOR} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.RADIATORfront} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.material_18} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.SPOILER} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.SUPORT1} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.WINDOWS} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.WINDOWrear} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.blackaluminium} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.blackmatte} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.brakelightsglass} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.carshadow} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.decal} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.detailplastic} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.detailsmatte} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.exhausthole} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.floor} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.fogglass} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.headlightsglass} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.lllllll} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.mirrorinterior} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.mirrors} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.plate} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.supportlogo} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.tire} />
      </group>
    </group>
  )
}

useGLTF.preload('/bmw.gltf')
